accounts/urls.py
from django.urls import path
from .views import MyLoginView , MyPasswordChangeView , MySignUpView
from django.contrib.auth.views import LogoutView

app_name = "accounts"
urlpatterns = [
    path("login/", MyLoginView.as_view() , name= 'login'),
    path("logout/", LogoutView.as_view() , name= 'logout'),
    path("password_change/", MyPasswordChangeView.as_view() , name= 'password_change'),
    path("signup/", MySignUpView.as_view() , name= 'signup')
]

site_1/urls.py
from django.contrib import admin
from django.urls import path , include
from viewer.views import hello , MoviesView , MoviesViewTemplate , MoviesViewList, MovieCreateView , GenreCreateView, MovieUpdateView, MovieDeleteView, MovieDetailView


admin.autodiscover()
# admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/<s0>/', hello, name="hello"),
    path('', MoviesViewList.as_view(), name="movies"), #class bassed view
    path('movie/create/', MovieCreateView.as_view(), name="movie_create"),
    path('genre/create/', GenreCreateView.as_view(), name="genre_create"),
    path('movie/update/<pk>/', MovieUpdateView.as_view(), name="movie_update"),
    path('movie/delete/<pk>/', MovieDeleteView.as_view(), name='movie_delete'),
    path('movie/detail/<pk>/', MovieDetailView.as_view(), name='movie_detail'),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]

viewer/models.py
from pyexpat.errors import messages

from django.db.models import Model , CharField , ForeignKey ,IntegerField , DateField , TextField , DateTimeField , DO_NOTHING , CASCADE

class Genre(Model):
    name = CharField(max_length=128)

    def __str__(self):
        return self.name

class Movie(Model):
  title = CharField(max_length=128)
  genre = ForeignKey(Genre, on_delete=CASCADE)
  rating = IntegerField()
  released = DateField()
  description = TextField()
  created = DateTimeField(auto_now_add=True)
  def __str__(self):
    #messages.success(self.request, "Movie added succesfully")
    return f"{self.title}, {self.released}: {self.genre}"

viewer/forms.py
import re
from datetime import date

from django.forms import (
    Form, CharField, ModelChoiceField, DateField, IntegerField, Textarea, ModelForm
)
from .models import Genre, Movie
from django.core.exceptions import ValidationError
#
# class MovieForm(Form):
#     title = CharField(max_length=128)
#     genre = ModelChoiceField(queryset=Genre.objects) #to choose a genre form the model(table
#     rating = IntegerField(min_value=1, max_value=10)
#     released = DateField()
#     descrption = CharField(widget=Textarea, required=False)


# This is a validator that checks if the value starts with a capital letter
# If not, it throws an ValidationError Exception
def capitalized_validator(value):
  if value[0].islower():
    raise ValidationError('Value must be capitalized.')

class PastDateField(DateField):
    def validate(self, value):
        super().validate(value)
        if value >= date.today():
            raise ValidationError('Only past dates allowed here.')
    def clean(self, value):
        result = super().clean(value)
        return date(year=result.year, month=result.month, day=1)

# This is a validator that checks if the value starts with a capital letter
# If not, it throws an ValidationError Exception
def capitalized_validator(value):
  if value[0].islower():
    raise ValidationError('Value must be capitalized.')
class PastDateField(DateField):
    def validate(self, value):
        super().validate(value)
        if value >= date.today():
            raise ValidationError('Only past dates allowed here.')
    def clean(self, value):
        result = super().clean(value)
        return date(year=result.year, month=result.month, day=1)
# class MovieForm(Form):
#     title = CharField(max_length=128, validators=[capitalized_validator])
#     genre = ModelChoiceField(queryset=Genre.objects) # To choose a Genre from the model (table) Genre
#     rating = IntegerField(min_value=1, max_value=10)
#     released = PastDateField()
#     description = CharField(widget=Textarea, required=False)
#
#     def clean_title(self):
#         return self.cleaned_data["title"] + "!!!"
#
#     def clean_description(self):
#         written_description = self.cleaned_data['description']
#         sentences = re.sub(r'\s*\s*', '.', written_description).split('.')
#         return '. '.join(sentence.capitalize() for sentence in sentences)
#
#     def clean(self):
#         result = super().clean()
#         if result['genre'].name == 'Comedy' and result['rating'] > 5:
#             self.add_error('genre', 'Comedy Genre')
#             self.add_error('rating', f'Rating:  {result["rating"]}')
#             raise ValidationError(
#                 "Comedies aren't so good to be rated over 5."
#             )
#         return result


class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = "__all__"
    released = PastDateField()
    rating = IntegerField(min_value=1, max_value=10)


class GenreForm(ModelForm):
    class Meta:
        model = Genre
        fields = "__all__"

viewer/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from .forms import MovieForm, GenreForm
from .models import Movie
from django.views import View
from django.views.generic import TemplateView, ListView, FormView, CreateView, UpdateView, DeleteView, DetailView
from django.http import HttpResponse
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, FormView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from logging import getLogger
from django.contrib import messages
LOGGER = getLogger()



# Create your views here.
def hello(request, s0):
    s1 = request.GET.get('s1', '')  # Get the variable s1 from the URL encoder
    return render(
        request, template_name='viewer/hello.html',  # Template is the file you want to load
        context={'adjectives': [s0, s1, 'beautiful', 'wonderful']} # context are the variable you send to the template
    )
# Function view to show movies
def movie_list(request):
    movie_list = Movie.objects.all()
    return render(
        request,
        template_name="viewer/movies.html",
        context={'movies': movie_list}
    )
# Class based view to show movies
class MoviesView(View):
    def get(self, request):
        movie_list = Movie.objects.all()
        return render(
            request,
            template_name="viewer/movies.html",
            context={'movies': movie_list}
        )
# Template view class
class MoviesViewTemplate(TemplateView):
    template_name = "viewer/movies.html"
    extra_context = {'movies': Movie.objects.all()}


#List view class
class MoviesViewList(ListView):
    template_name = "viewer/movies.html"
    model = Movie


# class MovieCreateView(FormView):
#     template_name = "viewer/movie_form.html"
#     form_class = MovieForm
#     success_url = reverse_lazy("movies")
#     def form_valid(self, form):
#         result = super().form_valid(form) # Validate the form
#         cleaned_data = form.cleaned_data # Get me the data from the form
#         Movie.objects.create(
#             title=cleaned_data['title'],
#             genre=cleaned_data['genre'],
#             rating=cleaned_data['rating'],
#             released=cleaned_data['released'],
#             description=cleaned_data['description']
#         )
#         return result
#     def form_invalid(self, form):
#         LOGGER.warning('User provided invalid data.')
#         return super().form_invalid(form)


# class MovieCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
#   template_name = 'viewer/movie_form.html'
#   form_class = MovieForm
#   success_url = reverse_lazy('movies')
#   permission_required = "viewer.add_movie"
#
#   def form_invalid(self, form):
#     LOGGER.warning('User provided invalid data.')
#     return super().form_invalid(form)
#
#
# class StaffRequiredMixin(UserPassesTestMixin):
#     def test_func(self):
#         return self.request.user.is_staff
#
#
class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff

class GenreCreateView(LoginRequiredMixin,PermissionRequiredMixin, StaffRequiredMixin, CreateView):
  template_name = 'viewer/genre_form.html'
  form_class = GenreForm
  success_url = reverse_lazy('movie_create')
  permission_required = "viewer.add_genre"

  def form_invalid(self, form):
    LOGGER.warning('User provided invalid data.')
    return super().form_invalid(form)
#
#
# class MovieUpdateView(LoginRequiredMixin,PermissionRequiredMixin, UpdateView):
#   template_name = 'viewer/genre_form.html'
#   model = Movie
#   form_class = MovieForm
#   success_url = reverse_lazy('movies')
#   permission_required = "viewer.change_movie"
#
#   def form_invalid(self, form):
#     LOGGER.warning('User provided invalid data.')
#     return super().form_invalid(form)
#
#
# class MovieDeleteView(LoginRequiredMixin,PermissionRequiredMixin, DeleteView):
#   template_name = 'viewer/delete_form.html'
#   model = Movie
#   success_url = reverse_lazy('movies')
#   permission_required = "viewer.delete_movie"
#
#
# class MovieDetailView(DetailView):
#   template_name = 'viewer/movie_details.html'
#   model = Movie



# Requires Log in, and Permission to add, and staff status
class MovieCreateView(LoginRequiredMixin, PermissionRequiredMixin, StaffRequiredMixin, CreateView):
  template_name = 'viewer/movie_form.html'
  form_class = MovieForm
  success_url = reverse_lazy('movies')
  permission_required = "viewer.add_movie"

  def form_valid(self, form):
      result = super().form_valid(form)
      messages.success(self.request, "Movie Added Successfully")
      return result


# Requires Log in, and Permission to change
class MovieUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = "viewer/movie_form.html"
    model = Movie
    form_class = MovieForm
    success_url = reverse_lazy("movies")
    permission_required = "viewer.change_movie"
    def form_invalid(self, form):
        LOGGER.warning('User provided invalid data.')
        return super().form_invalid(form)

# Requires Log in, and Permission to delete, and staff status and superuser status
class MovieDeleteView(LoginRequiredMixin, PermissionRequiredMixin, StaffRequiredMixin, DeleteView):
    template_name = "viewer/delete_form.html"
    model = Movie
    success_url = reverse_lazy("movies")
    permission_required = "viewer.delete_movie"
    def test_func(self):
        return super().test_func() and self.request.user.is_superuser
# It does not require any permissions nor Log in
class MovieDetailView(DetailView):
    template_name = "viewer/movie_details.html"
    model = Movie

viewer/templates/viewer/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HollyMovies</title>
    <!--    CSS BootStrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styl.css' %}">
    <link href='{% static "/css/styl.css" %}' rel='stylesheet' type='text/css'>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <!--    JS bootstrap   -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script>
        {% if messages %}
            {% for message in messages  %}
                alert('{{message}}')
            {% endfor %}
        {% endif %}
    </script>
</head>
<body>
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container fixed">
        <a class="navbar-brand" href="/">HollyMovies</a>
        <button
          class="navbar-toggler" type="button"
          data-toggle="collapse" data-target="#navbarNavAltMarkup"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'movies' %}">
              Home
            </a>
            <a class="nav-item nav-link active" href="{% url 'hello' 'creepy' %}">
              Hello
            </a>
            <a class="nav-item nav-link active" href="{% url 'hello' 'creepy' %}?s1=nice">
              Hi
            </a>
            <a class="nav-item nav-link active" href="{% url 'movie_create' %}">
              New Movie
            </a>
            <a class="nav-item nav-link active" href="{% url 'genre_create' %}">
              New Genre
            </a>
            <a class="nav-item nav-link active" href="/admin">
              Admin panel
            </a>

          </div>
        </div>

        <div class="navbar-nav ml-auto">
          <div class="nav-item dropdown">
            {% if user.is_authenticated %}
              <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                {% if user.first_name %}Hello, {{ user.first_name|capfirst  }}!
                {% else %}Hello, {{ user.username }}!{% endif %}
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item text-right" href="{% url 'accounts:logout' %}">Logout</a>
                <a class="dropdown-item text-right" href="{% url 'accounts:password_change' %}">Change password</a>
              </div>
            {% else %}
              <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                You are not logged in.
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item text-right" href="{% url 'accounts:login' %}">Login</a>
                <a class="dropdown-item text-right" href="{% url 'accounts:signup' %}">Sign up</a>
          </div>
        {% endif %}
        </div>
        </div>


    </div>
</nav>
<div class="container">
  <div class="jumbotron">
    {% block content %}{% endblock %}
  </div>
</div>
</body>
</html>

viewer/templates/viewer/delete_form.html
{% extends "viewer/base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %} 
    <p>
      Are you sure you want to delete movie "{{ object.title }}" from database?
    </p> 
    <input type="submit" value="Delete Movie" class="btn btn-danger">
  </form> 
{% endblock %}

viewer/templates/viewer/genre_form.html
{% extends "viewer/base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <table>{{ form }}</table>
    <input type="submit" value="submit" class="btn btn-primary">

</form>
{% endblock %}

viewer/templates/viewer/hello.html
{% extends "viewer/base.html" %}

{% block content %}
<h1>Welcome to HollyMovies!</h1>
    {% for adjective in adjectives %}
      {% if adjective != 'cruel' %}
        <p>This is a {{ adjective }} world...</p>
      {% endif %}
    {% endfor %}
{% endblock %}

viewer/templates/viewer/movie_details.html
{% extends "viewer/base.html" %}

{% block content %}
<h1>{{ object.title }}</h1>
<h2>{{ object.release }}</h2>
<h3>{{ object.genre }}</h3>
<p><strong> Rating:</strong>{{ object.rating}}</p>
<p> {{ object.description }}</p>
{% endblock %}

viewer/templates/viewer/movie_form.html
{% extends "viewer/base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <table>{{ form }}</table>
    <input type="submit" value="submit" class="btn btn-primary">

</form>
{% endblock %}

viewer/templates/viewer/movies.html
{% extends "viewer/base.html" %}
{% load static %}

{% block content %}
  <h1>Welcome to HollyMovies!</h1>
  <ul>
    {% for movie in object_list %}
      <li>
        {{ movie.title }} ({{ movie.released.year }}) : {{ movie.genre.name }} /
        <a href="{% url 'movie_detail' movie.id %}">
          Detail
        </a>
        {% if user.is_authenticated %} /
        <a href="{% url 'movie_update' movie.id %}">
          update
        </a> /
        <a href="{% url 'movie_delete' movie.id %}">
          Delete
        </a>
        {% endif %}
      </li>
    {% endfor %}
  </ul>

  <img src="{% static 'img/images.jpeg' %}" alt="Action!">
{% endblock %}